/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

// SQL SHIT GOES HERE
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;

// SQL ENDS HERE, THOT
/**
 *
 * @author Crestfall
 */
public class pms_menu_payslip_add extends javax.swing.JFrame {

    pms_global global = pms_global.INSTANCE;
    String url = global.pms_url;

    String currentemail;
    String salary_basic;
    String salary_perday;
    String salary_deduction;

    private void set_email(String lol) {
        currentemail = lol;
    }

    private String get_email() {
        return currentemail;
    }

    /**
     * Creates new form pms_menu_admin_add
     */
    public void pms_menu_payslip_add_init(String n) {
        initComponents();
        this.getRootPane().setDefaultButton(pms_menu_payslip_add_submit);
        this.set_email(n);
        try {
            Connection conn = DriverManager.getConnection(global.pms_url);

            // Because I'm a lazy prick. AND BECAUSE RS SUCKS
            Statement st1 = conn.prepareStatement(global.pms_url);
            Statement st2 = conn.prepareStatement(global.pms_url);
            Statement st3 = conn.prepareStatement(global.pms_url);

            ResultSet rs1 = st1.executeQuery("SELECT * from pms_settings WHERE settings = 'salary_basic'");
            ResultSet rs2 = st2.executeQuery("SELECT * from pms_settings WHERE settings = 'salary_perday'");
            ResultSet rs3 = st3.executeQuery("SELECT * from pms_settings WHERE settings = 'salary_deduction'");
            
            rs1.first();
            rs2.first();
            rs3.first();

            salary_basic = rs1.getString("value");
            salary_perday = rs2.getString("value");
            salary_deduction = rs3.getString("value");
        } catch (Exception e) {
            System.out.println("Error in initializing pms_menu_payslip_add.");
            System.out.println(e.getMessage());
        }
        pms_menu_payslip_add_refresh();
    }

    private void pms_menu_payslip_add_refresh() {
        pms_menu_payslip_add_workdays.setValue(20);
        pms_menu_payslip_add_leaves.setValue(0);
        pms_menu_payslip_add_salary_basic.setText(salary_basic);
        pms_menu_payslip_add_salary_perday.setText(salary_perday);
        pms_menu_payslip_add_salary_deduction.setText(salary_deduction);
        pms_menu_payslip_add_salary_net.setText("0");
        pms_menu_payslip_add_description.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pms_menu_payslip_add_submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pms_menu_payslip_add_salary_basic = new javax.swing.JTextField();
        pms_menu_payslip_add_salary_perday = new javax.swing.JTextField();
        pms_menu_payslip_add_salary_deduction = new javax.swing.JTextField();
        pms_menu_payslip_add_salary_net = new javax.swing.JTextField();
        pms_menu_payslip_add_calculate = new javax.swing.JButton();
        pms_menu_payslip_add_workdays = new javax.swing.JSpinner();
        pms_menu_payslip_add_leaves = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        pms_menu_payslip_add_description = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Add Payslip");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Leaves:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Workdays:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Basic Salary:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Salary Net:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Salary per Day:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Salary Deduction:");

        pms_menu_payslip_add_submit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_payslip_add_submit.setText("Submit");
        pms_menu_payslip_add_submit.setToolTipText("Submit to database.");
        pms_menu_payslip_add_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_payslip_add_submitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Description:");

        pms_menu_payslip_add_salary_basic.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        pms_menu_payslip_add_salary_perday.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        pms_menu_payslip_add_salary_deduction.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        pms_menu_payslip_add_salary_net.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        pms_menu_payslip_add_calculate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_payslip_add_calculate.setText("Calculate Net");
        pms_menu_payslip_add_calculate.setToolTipText("Submit to database.");
        pms_menu_payslip_add_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_payslip_add_calculateActionPerformed(evt);
            }
        });

        pms_menu_payslip_add_workdays.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        pms_menu_payslip_add_leaves.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        pms_menu_payslip_add_description.setColumns(20);
        pms_menu_payslip_add_description.setLineWrap(true);
        pms_menu_payslip_add_description.setRows(5);
        pms_menu_payslip_add_description.setToolTipText("");
        pms_menu_payslip_add_description.setWrapStyleWord(true);
        jScrollPane1.setViewportView(pms_menu_payslip_add_description);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pms_menu_payslip_add_calculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pms_menu_payslip_add_submit)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pms_menu_payslip_add_salary_basic, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pms_menu_payslip_add_salary_perday, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pms_menu_payslip_add_salary_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pms_menu_payslip_add_salary_net, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pms_menu_payslip_add_workdays, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pms_menu_payslip_add_leaves, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pms_menu_payslip_add_leaves, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pms_menu_payslip_add_workdays, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pms_menu_payslip_add_salary_basic, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pms_menu_payslip_add_salary_perday, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pms_menu_payslip_add_salary_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pms_menu_payslip_add_salary_net, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pms_menu_payslip_add_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pms_menu_payslip_add_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pms_menu_payslip_add_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_payslip_add_submitActionPerformed
        boolean tf = true;
        try {
            Double.parseDouble(pms_menu_payslip_add_salary_basic.getText());
            Double.parseDouble(pms_menu_payslip_add_salary_perday.getText());
            Double.parseDouble(pms_menu_payslip_add_salary_deduction.getText());
            Double.parseDouble(pms_menu_payslip_add_salary_net.getText());
        } catch (NumberFormatException e) {
            tf = false;
            System.out.println(e);
        }

        if (tf) {
            try {
                // Connection stuff.
                Connection conn = DriverManager.getConnection(url);
                // Date
                Date date = new java.util.Date();
                long time = date.getTime();
                Timestamp ts = new Timestamp(time);
                // Statements
                PreparedStatement prepstate_db = conn.prepareStatement("insert into pms_payslips (email, timestamp, workdays, leaves, salary_basic, salary_perday, salary_deduction, salary_net, description)" + " values (?, ?, ?, ?, ?, ?, ?, ?, ?)");

                prepstate_db.setString(1, this.get_email().toString());
                prepstate_db.setString(2, ts.toString());
                prepstate_db.setString(3, pms_menu_payslip_add_workdays.getValue().toString());
                prepstate_db.setString(4, pms_menu_payslip_add_leaves.getValue().toString());
                prepstate_db.setString(5, pms_menu_payslip_add_salary_basic.getText().toString());
                prepstate_db.setString(6, pms_menu_payslip_add_salary_perday.getText().toString());
                prepstate_db.setString(7, pms_menu_payslip_add_salary_deduction.getText().toString());
                prepstate_db.setString(8, pms_menu_payslip_add_salary_net.getText().toString());
                prepstate_db.setString(9, pms_menu_payslip_add_description.getText().toString());
                
                prepstate_db.execute();

                global.log(pms_global.log_user_payslip_add, this.get_email());
                
                JOptionPane.showMessageDialog(null, "Operation complete. Please check the database.");
                pms_menu_payslip_add_refresh();
            } catch (Exception e) {
                System.out.println("Error in editing data.");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            dispose();
        } else {
            // Phone number can only contain number
            JOptionPane.showMessageDialog(null, "Fields (excluding description field) can only contain numbers.");
        }
    }//GEN-LAST:event_pms_menu_payslip_add_submitActionPerformed

    private void pms_menu_payslip_add_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_payslip_add_calculateActionPerformed
        Integer n = Integer.parseInt(pms_menu_payslip_add_salary_basic.getText()) + ((Integer.parseInt(pms_menu_payslip_add_salary_perday.getText()) * Integer.parseInt(pms_menu_payslip_add_workdays.getValue().toString())) - (Integer.parseInt(pms_menu_payslip_add_salary_deduction.getText()) * Integer.parseInt(pms_menu_payslip_add_leaves.getValue().toString())));
        pms_menu_payslip_add_salary_net.setText(n.toString());
    }//GEN-LAST:event_pms_menu_payslip_add_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pms_menu_payslip_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pms_menu_payslip_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pms_menu_payslip_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pms_menu_payslip_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pms_menu_payslip_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pms_menu_payslip_add_calculate;
    private javax.swing.JTextArea pms_menu_payslip_add_description;
    private javax.swing.JSpinner pms_menu_payslip_add_leaves;
    private javax.swing.JTextField pms_menu_payslip_add_salary_basic;
    private javax.swing.JTextField pms_menu_payslip_add_salary_deduction;
    private javax.swing.JTextField pms_menu_payslip_add_salary_net;
    private javax.swing.JTextField pms_menu_payslip_add_salary_perday;
    private javax.swing.JButton pms_menu_payslip_add_submit;
    private javax.swing.JSpinner pms_menu_payslip_add_workdays;
    // End of variables declaration//GEN-END:variables

}
