/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/**
 *
 * @author Crestfall
 */
public class pms_menu_login extends javax.swing.JFrame {
    
    pms_global global = pms_global.INSTANCE;
    String url = global.pms_url;
    
    /**
     * Creates new form pms_menu_login
     */
    public pms_menu_login() {
        initComponents();
        this.getRootPane().setDefaultButton(pms_menu_login_button_submit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pms_menu_login_button_submit = new javax.swing.JButton();
        pms_menu_login_field_email = new javax.swing.JTextField();
        pms_menu_login_field_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Payroll Management System");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("LOGIN");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");

        pms_menu_login_button_submit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pms_menu_login_button_submit.setText("SUBMIT");
        pms_menu_login_button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_login_button_submitActionPerformed(evt);
            }
        });

        pms_menu_login_field_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_login_field_email.setMargin(new java.awt.Insets(0, 1, 0, 1));
        pms_menu_login_field_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_login_field_emailActionPerformed(evt);
            }
        });

        pms_menu_login_field_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_login_field_password.setMargin(new java.awt.Insets(0, 1, 0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pms_menu_login_button_submit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pms_menu_login_field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pms_menu_login_field_email, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pms_menu_login_field_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pms_menu_login_field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pms_menu_login_button_submit)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pms_menu_login_button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_login_button_submitActionPerformed

        try {
            // LETS CONNECT, GET URL FROM PMS_GLOBAL
//            pms_global global = new pms_global();
//            String url = global.pms_url;
            Connection conn = DriverManager.getConnection(url);
            // GET TIMESTAMP
            java.util.Date date = new java.util.Date();
            long time = date.getTime();
            Timestamp ts = new Timestamp(time);
            // CONNECTION, BASIC VAR, STUFF
            String dbEmail = pms_menu_login_field_email.getText();
            String dbPassword = pms_menu_login_field_password.getText();
            PreparedStatement prepstate = conn.prepareStatement("SELECT * FROM pms_user WHERE email= ? && password= ?");
            prepstate.setString(1, dbEmail);
            prepstate.setString(2, dbPassword);
            ResultSet resuset = prepstate.executeQuery();
            if (resuset.next()) {
                System.out.println("WE GOT EM BOYS");
                // LOGGING PURPOSES
                PreparedStatement prepstate_log = conn.prepareStatement(" insert into pms_log (email, timestamp, activity)" + " values (?, ?, ?)");
                prepstate_log.setString(1, pms_menu_login_field_email.getText());
                prepstate_log.setString(2, ts.toString());
                prepstate_log.setString(3, pms_global.log_user_login);
                System.out.println("LOG: LOGIN USER: " + pms_menu_login_field_email.getText());
                prepstate_log.execute();
                // SESSION SYSTEM
                global.set_data(pms_menu_login_field_email.getText());
                // CHECK YOUR RIGHTS
                if (global.get_rights().equals("admin")) {
                    new pms_menu_admin().setVisible(true);
                } else if (global.get_rights().equals("manager")) {
                    new pms_menu_manager().setVisible(true);
                } else {
                    new pms_menu_employee().setVisible(true);
                }
                // WERE DONE HERE BYE BOY
                dispose();
            } else {
                System.out.println("WHAT? NOT FOUND!!!!!!");
                JOptionPane.showMessageDialog(null, "Account not found. Please check your username and password.");
            }

        } catch (Exception e) {
            System.out.println("Error in logging in.");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_pms_menu_login_button_submitActionPerformed

    private void pms_menu_login_field_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_login_field_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pms_menu_login_field_emailActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pms_menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pms_menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pms_menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pms_menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pms_menu_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton pms_menu_login_button_submit;
    private javax.swing.JTextField pms_menu_login_field_email;
    private javax.swing.JPasswordField pms_menu_login_field_password;
    // End of variables declaration//GEN-END:variables
}
