/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

// SQL SHIT GOES HERE
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Crestfall
 */
public class pms_menu_newmessage extends javax.swing.JFrame {

    pms_global global = pms_global.INSTANCE;
    String url = global.pms_url;

    /**
     * Creates new form pms_menu_message
     *
     * @param id
     */
    public pms_menu_newmessage() {
        initComponents();
        this.getRootPane().setDefaultButton(pms_menu_newmessage_submit);

        pms_menu_newmessage_combo.removeAllItems();
        // Get combobox value from database
        try {
            Connection conn = DriverManager.getConnection(url);
            Statement st = conn.prepareStatement(url);
            ResultSet rs = st.executeQuery("select email from pms_user");
            while (rs.next()) {
                pms_menu_newmessage_combo.addItem(rs.getString("email"));
            }
        } catch (Exception e) {
            System.out.println("Error in getting items from combo.");
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pms_menu_newmessage_submit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pms_menu_newmessage_message = new javax.swing.JTextArea();
        pms_menu_newmessage_combo = new javax.swing.JComboBox<>();
        pms_menu_newmessage_subject = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Message");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Receiver:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Subject:");

        pms_menu_newmessage_submit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_newmessage_submit.setText("Submit");
        pms_menu_newmessage_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_newmessage_submitActionPerformed(evt);
            }
        });

        pms_menu_newmessage_message.setColumns(20);
        pms_menu_newmessage_message.setLineWrap(true);
        pms_menu_newmessage_message.setRows(5);
        pms_menu_newmessage_message.setWrapStyleWord(true);
        pms_menu_newmessage_message.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jScrollPane2.setViewportView(pms_menu_newmessage_message);

        pms_menu_newmessage_combo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        pms_menu_newmessage_subject.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_newmessage_subject.setMargin(new java.awt.Insets(0, 1, 0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pms_menu_newmessage_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pms_menu_newmessage_subject, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(pms_menu_newmessage_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(pms_menu_newmessage_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(pms_menu_newmessage_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pms_menu_newmessage_submit, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pms_menu_newmessage_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_newmessage_submitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to submit?", "Warning", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            try {
                // Connection stuff.
                pms_global global = pms_global.INSTANCE;
                String url = global.pms_url;
                Connection conn = DriverManager.getConnection(url);

                Date date = new java.util.Date();
                long time = date.getTime();
                Timestamp ts = new Timestamp(time);
                // Statements
                PreparedStatement prepstate_db = conn.prepareStatement(" insert into pms_messages (sender, receiver, subject, timestamp, message)" + " values (?, ?, ?, ?, ?)");
                prepstate_db.setString(1, global.get_email());
                prepstate_db.setString(2, (String) pms_menu_newmessage_combo.getSelectedItem().toString());
                prepstate_db.setString(3, pms_menu_newmessage_subject.getText());
                prepstate_db.setString(4, ts.toString());
                prepstate_db.setString(5, pms_menu_newmessage_message.getText());
                global.log(pms_global.log_user_message, pms_menu_newmessage_combo.getSelectedItem().toString());
                // Execute
                prepstate_db.execute();
                JOptionPane.showMessageDialog(null, "Message sent!");
                dispose();
            } catch (Exception e) {
                System.out.println("Error in sending message.");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_pms_menu_newmessage_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pms_menu_newmessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pms_menu_newmessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pms_menu_newmessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pms_menu_newmessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pms_menu_newmessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> pms_menu_newmessage_combo;
    private javax.swing.JTextArea pms_menu_newmessage_message;
    private javax.swing.JTextField pms_menu_newmessage_subject;
    private javax.swing.JButton pms_menu_newmessage_submit;
    // End of variables declaration//GEN-END:variables

}
