/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

// SQL SHIT GOES HERE
import java.sql.*;
import javax.swing.JOptionPane;

// SQL ENDS HERE, THOT
/**
 *
 * @author Crestfall
 */
public class pms_menu_manager_add extends javax.swing.JFrame {

    /**
     * Creates new form pms_menu_admin_add
     */
    public pms_menu_manager_add() {
        initComponents();
        this.getRootPane().setDefaultButton(pms_menu_manager_add_button_submit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pms_menu_manager_add_field_email = new javax.swing.JTextField();
        pms_menu_manager_add_field_name = new javax.swing.JTextField();
        pms_menu_manager_add_field_role = new javax.swing.JTextField();
        pms_menu_manager_add_combo_rights = new javax.swing.JComboBox<>();
        pms_menu_manager_add_button_submit = new javax.swing.JButton();
        pms_menu_manager_add_button_clear = new javax.swing.JButton();
        pms_menu_manager_add_spinner_level = new javax.swing.JSpinner();
        pms_menu_manager_add_field_phone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Register");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Rights:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Level:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Role:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Phone:");

        pms_menu_manager_add_combo_rights.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "employee" }));

        pms_menu_manager_add_button_submit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_manager_add_button_submit.setText("Submit");
        pms_menu_manager_add_button_submit.setToolTipText("Submit to database.");
        pms_menu_manager_add_button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_manager_add_button_submitActionPerformed(evt);
            }
        });

        pms_menu_manager_add_button_clear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_manager_add_button_clear.setText("Clear");
        pms_menu_manager_add_button_clear.setToolTipText("Clear fields.");
        pms_menu_manager_add_button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_manager_add_button_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pms_menu_manager_add_field_email)
                                .addComponent(pms_menu_manager_add_field_name, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(pms_menu_manager_add_field_role, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(pms_menu_manager_add_combo_rights, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pms_menu_manager_add_spinner_level)
                                    .addGap(155, 155, 155))
                                .addComponent(pms_menu_manager_add_field_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pms_menu_manager_add_button_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pms_menu_manager_add_button_submit)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pms_menu_manager_add_field_email, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pms_menu_manager_add_combo_rights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pms_menu_manager_add_field_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pms_menu_manager_add_field_role))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pms_menu_manager_add_field_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pms_menu_manager_add_spinner_level))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pms_menu_manager_add_button_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pms_menu_manager_add_button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pms_menu_admin_add_clear() {
        System.out.println("pms_menu_admin_add: Resetting all fields.");
        pms_menu_manager_add_field_email.setText("");
        pms_menu_manager_add_spinner_level.setValue(0);
        pms_menu_manager_add_field_name.setText("");
        pms_menu_manager_add_field_phone.setText("0");
        pms_menu_manager_add_field_role.setText("");
        pms_menu_manager_add_combo_rights.setSelectedItem("employee");
    }

    private void pms_menu_manager_add_button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_manager_add_button_clearActionPerformed
        pms_menu_admin_add_clear();
    }//GEN-LAST:event_pms_menu_manager_add_button_clearActionPerformed

    private void pms_menu_manager_add_button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_manager_add_button_submitActionPerformed
        boolean tf = true;
        try {
            Double.parseDouble(pms_menu_manager_add_field_phone.getText());
        } catch (NumberFormatException e) {
            tf = false;
        }

        if (tf) {
            System.out.println("ATTEMPT TO SUBMIT");
            try {
                // Connection stuff.
                pms_global global = pms_global.INSTANCE;
                String url = global.pms_url;
                Connection conn = DriverManager.getConnection(url);
                // Statements
                PreparedStatement prepstate_db = conn.prepareStatement(" insert into pms_user (email, rights, name, role, phone, level)" + " values (?, ?, ?, ?, ?, ?)");
                prepstate_db.setString(1, pms_menu_manager_add_field_email.getText());
                prepstate_db.setString(2, (String) pms_menu_manager_add_combo_rights.getSelectedItem());
                prepstate_db.setString(3, pms_menu_manager_add_field_name.getText());
                prepstate_db.setString(4, pms_menu_manager_add_field_role.getText());
                prepstate_db.setString(5, pms_menu_manager_add_field_phone.getText());
                prepstate_db.setString(6, ((Integer) pms_menu_manager_add_spinner_level.getValue()).toString());
                global.log(pms_global.log_user_add, pms_menu_manager_add_field_email.getText());
                // Execute
                prepstate_db.execute();
                pms_menu_admin_add_clear();
                JOptionPane.showMessageDialog(null, "Operation complete. Please check the database.");
                System.out.println("CLEAR FIELDS, SUBMIT SUCCESSFUL... I THINK");
            } catch (Exception e) {
                System.out.println("BRO FIX YOUR SHIT NIGGA");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            // Phone number can only contain number
            System.out.println("FOOK YOU PHONE IS NUMBER ONLY BIATCH");
            JOptionPane.showMessageDialog(null, "Phone field can only contain numbers. Reset to 0.");
            pms_menu_manager_add_field_phone.setText("0");
        }
    }//GEN-LAST:event_pms_menu_manager_add_button_submitActionPerformed

//    HERE COMES DEPRECATED METHOD
//    private void pms_menu_admin_add_field_phone_removeAlphabet() {
//    System.out.println("NO MORE OF YOU ALPHABET THOTS, BEGONE");
//    String x = pms_menu_admin_add_field_phone.getText();
//    Scanner sc = new Scanner(x);    
//    String lol = sc.nextLine();
//    if (lol.equals("")) {
//    } else {
//    lol.replaceAll("[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ]", "");
//    pms_menu_admin_add_field_phone.setText(lol);
//    pms_menu_admin_add_field_phone.repaint();
//    }
//}
//    FUCKING USELESS CHAP
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pms_menu_manager_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton pms_menu_manager_add_button_clear;
    private javax.swing.JButton pms_menu_manager_add_button_submit;
    private javax.swing.JComboBox<String> pms_menu_manager_add_combo_rights;
    private javax.swing.JTextField pms_menu_manager_add_field_email;
    private javax.swing.JTextField pms_menu_manager_add_field_name;
    private javax.swing.JTextField pms_menu_manager_add_field_phone;
    private javax.swing.JTextField pms_menu_manager_add_field_role;
    private javax.swing.JSpinner pms_menu_manager_add_spinner_level;
    // End of variables declaration//GEN-END:variables

}
