/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

// SQL SHIT GOES HERE
import java.sql.*;
import javax.swing.JOptionPane;

// SQL ENDS HERE, THOT
/**
 *
 * @author Crestfall
 */
public class pms_menu_manager_edit extends javax.swing.JFrame {

    pms_global global = pms_global.INSTANCE;
    String url = global.pms_url;

    /**
     * Creates new form pms_menu_admin_edit
     */
    public pms_menu_manager_edit() {
        initComponents();
        this.getRootPane().setDefaultButton(pms_menu_admin_edit_button_submit);
        
        try {
            Connection conn = DriverManager.getConnection(url);
            Statement st = conn.prepareStatement(url);
            ResultSet rs = st.executeQuery("select email from pms_user");
            while (rs.next()) {
                pms_menu_admin_edit_comboemail.addItem(rs.getString("email"));
            }
        } catch (Exception e) {
            System.out.println("Error in getting items from combo.");
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        select();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pms_menu_admin_edit_field_name = new javax.swing.JTextField();
        pms_menu_admin_edit_field_role = new javax.swing.JTextField();
        pms_menu_admin_edit_combo_rights = new javax.swing.JComboBox<>();
        pms_menu_admin_edit_button_submit = new javax.swing.JButton();
        pms_menu_admin_edit_spinner_level = new javax.swing.JSpinner();
        pms_menu_admin_edit_field_phone = new javax.swing.JTextField();
        pms_menu_admin_edit_comboemail = new javax.swing.JComboBox<>();
        pms_menu_admin_edit_select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Edit");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Rights:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Level:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Role:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Phone:");

        pms_menu_admin_edit_combo_rights.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "employee", "manager", "admin" }));

        pms_menu_admin_edit_button_submit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pms_menu_admin_edit_button_submit.setText("Submit");
        pms_menu_admin_edit_button_submit.setToolTipText("Submit to database.");
        pms_menu_admin_edit_button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_admin_edit_button_submitActionPerformed(evt);
            }
        });

        pms_menu_admin_edit_comboemail.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pms_menu_admin_edit_comboemailItemStateChanged(evt);
            }
        });

        pms_menu_admin_edit_select.setText("Select");
        pms_menu_admin_edit_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pms_menu_admin_edit_selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pms_menu_admin_edit_button_submit)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pms_menu_admin_edit_combo_rights, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pms_menu_admin_edit_spinner_level, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pms_menu_admin_edit_field_role, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(pms_menu_admin_edit_field_name)
                                .addComponent(pms_menu_admin_edit_field_phone)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pms_menu_admin_edit_comboemail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pms_menu_admin_edit_select))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pms_menu_admin_edit_comboemail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pms_menu_admin_edit_select))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pms_menu_admin_edit_combo_rights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pms_menu_admin_edit_field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pms_menu_admin_edit_field_role, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pms_menu_admin_edit_field_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pms_menu_admin_edit_spinner_level, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(pms_menu_admin_edit_button_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pms_menu_admin_edit_button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_admin_edit_button_submitActionPerformed
        boolean tf = true;
        try {
            Double.parseDouble(pms_menu_admin_edit_field_phone.getText());
        } catch (NumberFormatException e) {
            tf = false;
        }

        if (tf) {
            try {
                // Connection stuff.
                Connection conn = DriverManager.getConnection(url);
                Statement st = conn.createStatement();
                // Statements
                st.executeUpdate("UPDATE pms_user SET rights = '" + (String) pms_menu_admin_edit_combo_rights.getSelectedItem().toString() + "' WHERE email = '" + pms_menu_admin_edit_comboemail.getSelectedItem().toString() + "'");
                st.executeUpdate("UPDATE pms_user SET name = '" + pms_menu_admin_edit_field_name.getText() + "' WHERE email = '" + pms_menu_admin_edit_comboemail.getSelectedItem().toString() + "'");
                st.executeUpdate("UPDATE pms_user SET role = '" + pms_menu_admin_edit_field_role.getText() + "' WHERE email = '" + pms_menu_admin_edit_comboemail.getSelectedItem().toString() + "'");
                st.executeUpdate("UPDATE pms_user SET phone = '" + pms_menu_admin_edit_field_phone.getText() + "' WHERE email = '" + pms_menu_admin_edit_comboemail.getSelectedItem().toString() + "'");
                st.executeUpdate("UPDATE pms_user SET level = '" + (Integer) pms_menu_admin_edit_spinner_level.getValue() + "' WHERE email = '" + pms_menu_admin_edit_comboemail.getSelectedItem().toString() + "'");
                global.log(pms_global.log_user_edit, pms_menu_admin_edit_comboemail.getSelectedItem().toString());
                JOptionPane.showMessageDialog(null, "Operation complete. Please check the database.");
            } catch (Exception e) {
                System.out.println("Error in editing data.");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            // Phone number can only contain number
            System.out.println("Phone field can only contain numbers.");
            JOptionPane.showMessageDialog(null, "Phone field can only contain numbers. Reset to 0.");
            pms_menu_admin_edit_field_phone.setText("0");
        }
    }//GEN-LAST:event_pms_menu_admin_edit_button_submitActionPerformed

    private void pms_menu_admin_edit_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pms_menu_admin_edit_selectActionPerformed
        select();
    }//GEN-LAST:event_pms_menu_admin_edit_selectActionPerformed

    private void pms_menu_admin_edit_comboemailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pms_menu_admin_edit_comboemailItemStateChanged
        select();
    }//GEN-LAST:event_pms_menu_admin_edit_comboemailItemStateChanged

    private void select() {
    try {
            // Connections
            Connection conn = DriverManager.getConnection(url);
            Statement st = conn.prepareStatement(url);
            ResultSet rs = st.executeQuery("SELECT * from pms_user WHERE email LIKE '" + pms_menu_admin_edit_comboemail.getSelectedItem().toString() + "'");
            while (rs.next()) {
                String a = rs.getString("name");
                String b = rs.getString("role");
                String c = rs.getString("phone");
                String d = rs.getString("level");
                Integer d_int = Integer.parseInt(d);
                String e = rs.getString("rights");

                pms_menu_admin_edit_field_name.setText(a);
                pms_menu_admin_edit_field_role.setText(b);
                pms_menu_admin_edit_field_phone.setText(c);
                pms_menu_admin_edit_spinner_level.setValue(d_int);
                if (e.equals("admin")) {
                    pms_menu_admin_edit_combo_rights.setSelectedIndex(2);
                } else if (e.equals("manager")) {
                    pms_menu_admin_edit_combo_rights.setSelectedIndex(1);
                } else {
                    pms_menu_admin_edit_combo_rights.setSelectedIndex(0);
                }
            }
            System.out.println("Get userdata from database.");
        } catch (Exception e) {
            System.out.println("User data error.");
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pms_menu_manager_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pms_menu_manager_edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton pms_menu_admin_edit_button_submit;
    private javax.swing.JComboBox<String> pms_menu_admin_edit_combo_rights;
    private javax.swing.JComboBox<String> pms_menu_admin_edit_comboemail;
    private javax.swing.JTextField pms_menu_admin_edit_field_name;
    private javax.swing.JTextField pms_menu_admin_edit_field_phone;
    private javax.swing.JTextField pms_menu_admin_edit_field_role;
    private javax.swing.JButton pms_menu_admin_edit_select;
    private javax.swing.JSpinner pms_menu_admin_edit_spinner_level;
    // End of variables declaration//GEN-END:variables

}
